### ISSUE TITLE
focusedIndex sends the inputs to `console.log`

### ISSUE THREAD

**Issue by renardeinside** [VerburgtJimmy/svelte-input-otp#3] opened 2024-08-06 20:01 UTC
### Describe the bug

See line:

https://github.com/VerburgtJimmy/svelte-input-otp/blob/8258a56af24dcd443bf2fbc0b782d65b871784f9/src/lib/input-otp-root.svelte#L52

Not sure if it introduces any unsafety, but definitely shouldn't be there.

### Reproduction

N/AA

### System Info

```bash
N/A
```

### Severity

annoyance

**Comment by VerburgtJimmy** [comment] 2024-08-27 15:56
I just got back from vacation. Thank you for notifying this issue. I will fix it in the next minor release. I hope next week i will have the time.

**Comment by VerburgtJimmy** [comment] 2024-08-30 18:24
Closing issue as the issue is resolved in the new v0.0.3 release.

**Closed by VerburgtJimmy** 2024-08-30 18:24 UTC
Labels: type: annoyance, status: accepted
